In [1]:
!pip install numpy

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/72/b2/02770e60c4e2f7e158d923ab0dea4e9f146a2dbf267fec6d8dc61d475689/numpy-1.25.2-cp311-cp311-win_amd64.whl.metadata
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB 262.6 kB/s eta 0:01:00
   ---------------------------------------- 0.0/15.5 MB 281.8 kB/s eta 0:00:56
   ---------------------------------------- 0.1/15.5 MB 393.8 kB/s eta 0:00:40
    --------------------------------------- 0.2/15.5 MB 841.6 kB/s eta 0:00:19
    --------------------------------------- 0.3/15.5 MB 1.0 MB/s eta 0:00:15
   - -------------------------------------- 0.5/15.5 MB 1.4 MB/s eta 0:00:11
   - -------------------------------------- 0.5/15.5 MB 1.4 MB/s eta 0:00:11
   - ---------------------------------

In [2]:
!pip install pandas

  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/b7/f8/32d6b5aa4c4bc045fa2c4c58f88c325facc54721956c6313f0afea8ea853/pandas-2.1.0-cp311-cp311-win_amd64.whl.metadata
     ---------------------------------------- 0.0/502.3 kB ? eta -:--:--
     ---------------------------------------- 0.0/502.3 kB ? eta -:--:--
     ---------------------------------------- 0.0/502.3 kB ? eta -:--:--
     ---------------------------------------- 0.0/502.3 kB ? eta -:--:--
      --------------------------------------- 10.2/502.3 kB ? eta -:--:--
      --------------------------------------- 10.2/502.3 kB ? eta -:--:--
      --------------------------------------- 10.2/502.3 kB ? eta -:--:--
      --------------------------------------- 10.2/502.3 kB ? eta -:--:--
     -- ---------------------------------- 30.7/502.3 kB 108.9 kB/s eta 0:00:05
     -- ---------------------------------- 30.7/502.3 kB 108.9 kB/s eta 0:00:05
     -- ---------------------------------- 30.

In [25]:
import numpy as np

a = np.random.randint(0, 100, size=(10))
print(a)
print(a.dtype)


[63 92 72 46 99 53  7 88 70 66]
int32


In [52]:
b = np.random.rand(5,5)
print(b)
print("min: ", b.min())
print("max: ", b.max())
print("med: ", b.mean())

[[0.89114973 0.83368808 0.97971828 0.67375889 0.04263226]
 [0.31542377 0.50456075 0.61551262 0.56010713 0.99532748]
 [0.54530075 0.58727976 0.9905578  0.12000532 0.65308109]
 [0.84386169 0.13711214 0.27972022 0.4886827  0.62976881]
 [0.12392454 0.48428075 0.09169209 0.4809128  0.52267181]]
min:  0.042632258440412185
max:  0.9953274837776415
med:  0.5356292509068961


In [38]:
c = np.random.rand(1, 10)
c10 = c*10
int_c10 = c10.astype(int)

print(c)
print(c10)
print(int_c10)

[[0.47537429 0.01923579 0.17400178 0.83152464 0.15767758 0.06318467
  0.40179442 0.98683148 0.33418521 0.41771872]]
[[4.75374292 0.19235794 1.74001784 8.31524642 1.57677584 0.63184674
  4.01794422 9.86831477 3.34185214 4.17718725]]
[[4 0 1 8 1 0 4 9 3 4]]


In [60]:
d = np.random.randint(0, 10, size=(3, 3))
print(d)

d[1, :] = -11

print(d)

[[6 9 0]
 [6 5 5]
 [2 4 5]]
[[  6   9   0]
 [-11 -11 -11]
 [  2   4   5]]


In [62]:
import pandas as pd

e = {'fruta': ['Banana', 'Maçã', 'Pera'],
      'preço': [7.90, 10.20, 11.80],
      'quantidade': [12, 3, 4]}

pd.DataFrame(e)



fruta  preço  quantidade
0  Banana    7.9          12
1    Maçã   10.2           3
2    Pera   11.8           4